### ISSUE TITLE
AI-Render not communicate with the local server on Mac

### ISSUE THREAD

**Issue by nickbelomatis** [benrugg/AI-Render#128]
### Describe the bug

loc("mps_add"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/75428952-3aa4-11ee-8b65-46d450270006/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":233:0)): error: input types 'tensor<2x1280xf32>' and 'tensor<1280xf16>' are not broadcast compatible
LLVM ERROR: Failed to infer result type(s).
./webui.sh: line 255: 40034 Abort trap: 6           "${python_cmd}" -u "${LAUNCH_SCRIPT}" "$@"
/opt/homebrew/Cellar/python@3.10/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

### To reproduce

Stable Diffusion works properly but AI-Render can't connect with the local server.

### Error log

The local Stable Diffusion server couldn't be found. It's either not running, or it's running at a different location than what you specified in the add-on preferences.

### Environment

- Blender version (upper right corner of splash screen): 
- AI Render version (find in Preferences > Add-ons): 
- Operating system (Windows/Mac/Linux):

**Comment by benrugg** [comment]
I've been looking into this and #129 for a while. It looks like your error is with Automatic1111, not with AI Render. (Your error log shows Automatic1111 crashing). 

Here's what I would suggest:
1. Make sure Automatic1111 is updated. (It used to auto-update when run, but it doesn't do that anymore!). In a terminal window, change directory to Automatic1111 `cd wherever` and then run `git stash; git pull; git stash pop`
2. Make sure you have `--api` in `COMMANDLINE_ARGS` in the file `webui-user.sh`. Since you're on a mac, it should probably be something like this: `export COMMANDLINE_ARGS="--skip-torch-cuda-test --upcast-sampling --no-half-vae --api --use-cpu interrogate"`
3. Double check that Automatic1111 works in the web ui. 

If you still have an issue after that, let me know and I'll reopen this issue. Please send me the log from Blender in addition to the one from Automatic1111. You can get it by following these steps:

- Close Blender and then open the Terminal app
- Run cd /Applications/Blender.app/Contents/MacOS && ./Blender
- Do whatever causes the bug
- Copy and paste the error you see in the Terminal

**Comment by nickbelomatis** [comment]
I follow all the steps but still don't work.

Device with name Apple M2 Pro supports metal minimum requirements
METAL API - DETECTED GPU: Apple M2 Pro
2023-10-09 09:24:32.161 Blender[42905:2534236] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
AI Render Error: It looks like the Automatic1111 server is running, but it's not in API mode. [Get help](https://github.com/benrugg/AI-Render/wiki/Local-Installation#troubleshooting)

**Comment by nickbelomatis** [comment]
AI Render Error: The local Stable Diffusion server couldn't be found. It's either not running, or it's running at a different location than what you specified in the add-on preferences. [Get help](https://github.com/benrugg/AI-Render/wiki/Local-Installation)

![Image](https://github.com/benrugg/AI-Render/assets/5521094/5619b9d6-8be6-4a4f-9bb5-5f6ee5426e28)

**Comment by nickbelomatis** [comment]
So, I don't know why but I run those commands on terminal and now works.

brew update && brew upgrade && brew install openssl
cd /usr/local/Cellar/openssl/1.0.2t/lib
sudo cp libssl.1.0.0.dylib libcrypto.1.0.0.dylib /usr/local/lib/
cd /usr/local/lib
sudo ln -s libssl.1.0.0.dylib libssl.dylib
sudo ln -s libcrypto.1.0.0.dylib libcrypto.dylib
pip3 install --upgrade packagename

**Comment by benrugg** [comment]
Ok, really glad you got it working. Yeah, Automatic1111 is a beast. It can be such a headache. I wish they made it easier and more stable!
