### ISSUE TITLE
Will not render animation

### ISSUE THREAD

**Issue by imnotliveyet** [benrugg/AI-Render#130]
### Describe the bug

States that I must click "Render animation" button to render animation when rendering animation.

### To reproduce

Create basic animation, set prompts, render animation.

### Error log

AI Render Error: To render an animation with AI Render, use the "Render Animation" button in the Animation panel below

### Environment

- Blender version (upper right corner of splash screen): 4.1
- AI Render version (find in Preferences > Add-ons): 0.9.1
- Operating system (Windows/Mac/Linux): Windows 10

### Screenshots/video

https://github.com/benrugg/AI-Render/assets/128502425/d234c6ca-9920-432c-9f2c-a3fa0e6f8768

**Comment by benrugg** [comment]
Yes, unfortunately Blender gives add-on developers very limited access in a lot of different areas. I can't hook into the standard animation rendering pipeline and I had to create my own. So instead of doing the standard "render animation" button in the Blender menu, you need to click the button in the AI Render panel, under the "Animation" heading. 

I just realized that the wording of my error message doesn't make that very clear, though 🤦‍♂️

**Comment by benrugg** [comment]
Just in case I wasn't clear enough - find the "Render Animation" button in the AI Render panels!

**Comment by imnotliveyet** [comment]
Ah, I tried looking there but saw nothing because it was greyed out. Maybe set the default path to C:\tmp\?

**Comment by benrugg** [comment]
Ah yes, just enter a path first. That's probably another thing I could improve in the UI!
