### ISSUE TITLE
SDXL Compatability

### ISSUE THREAD

**Issue by ElevatorTwelve** [benrugg/AI-Render#142]
### Describe the feature you'd like to see:

Such an amazing add on!

I 've been running it with Blender 4.0 and the latest version of Automatic 1111 and discovered that I can impact the final look by switching between checkpoint models. Unfortunately it seems to only respond to SD1.5 models, but I'm hoping there is a future in sight where we can use SDXL, or SDXL turbo and possibly loras.

**Comment by benrugg** [comment]
Hmm, there must be something else going on. I've been using AI Render with SDXL since it was released (on both DreamStudio and Automatic1111). 

I'd suggest testing your SDXL model directly in the Automatic1111 interface, or maybe messing with the image size settings in Blender to make sure they're supported.
