### ISSUE TITLE
when enabling addon it shows error in red color

### ISSUE THREAD

**Issue by vuaieo** [benrugg/AI-Render#156]
### Describe the bug

hello i downloaded the comfyui branch and installed it and when enabled it shows this :

![Screenshot_20241025_063645](https://github.com/user-attachments/assets/07760f80-ca55-40cf-a983-522069bf845b)

i am using linux and tryed on 4.2 to 4.4 blender versions but its same everywhere 🥶

### To reproduce

just installing addon and enable it

### Error log

there is no error log in terminal :(

### Environment

- Blender version (upper right corner of splash screen): 
- AI Render version (find in Preferences > Add-ons): 
- Operating system (Windows/Mac/Linux):  LINUX

**Comment by benrugg** [comment]
Ah, yes, I see you're using the ComfyUI branch. There's an issue where Github adds a top level folder inside the zip file when you download, and it breaks what Blender is expecting to see. 

The fix is to unzip AI Render, and then rezip all the files without the top level folder. You can also see the instructions here: https://github.com/benrugg/AI-Render/blob/comfyui-support/README_comfy.md#installation-of-comfyui

In the near future, as soon as this [PR is merged](https://github.com/benrugg/AI-Render/pull/154), this won't be an issue anymore!

**Comment by vuaieo** [comment]
hi just wanted to say i did what yo said and i unpacked it and then zipped all the files in the AI-Render-comfyui-support like that:
![compressed_again](https://github.com/user-attachments/assets/41fa2319-dc06-40d6-951b-d6f99613120c)

then installed it but it doesnt even show up and did not get transfered in the /home/vuaieo/.config/upbge/4.4/scripts/addons/

so i then i just placed that "AI-Render-comfyui-support" unpacked folder from zip myself in the /home/vuaieo/.config/upbge/4.4/scripts/addons/ but the messege when enabling is the same. it happends on the blender LTS 4.2.3 too T___T

**Comment by benrugg** [comment]
Hey, sorry this still isn't working. I'm honestly not sure how to help. We are working on fully releasing ComfyUI support, so hopefully that will be ready soon!
