### ISSUE TITLE
Sampler steps is off by (half + 1)

### ISSUE THREAD

**Issue by amerizalde** [benrugg/AI-Render#30]
### Describe the bug

using the current release, for any sampler, the steps actually ran are (half the steps requested + 1). The default of 40 runs 21 steps, when I set it to 80, it ran 41 steps.

### To reproduce

using 0.4.01, running Automatic1111 locally on Windows, render any blend file with the default AI-Render settings. Check the cmd window output from Automatic1111 to see the progress of the sampler.

### Error log

No errors found. Does not crash Blender or Automatic1111 api.

### Environment

- Blender version (upper right corner of splash screen): 3.3.1
- AI Render version (find in Preferences > Add-ons): 0.4.01
- Operating system (Windows/Mac/Linux): Window 10

### Screenshots/video

![Capture](https://user-images.githubusercontent.com/4033112/200653963-395f042e-4d89-4f3d-893f-7ffea72c18ce.PNG)

**Comment by benrugg** [comment]
@amerizalde Thanks for posting this. I've seen this on my end as well. I had thought it was actually an error on Automatic1111's end. Can you confirm that this doesn't happen when running through the Automatic1111 web UI?

**Comment by amerizalde** [comment]
Automatic1111 is what I was comparing it against, it doesn't occur there when accessed through the api using PaintHUA or the webui.

**Comment by benrugg** [comment]
Ok, thanks for confirming that. I will dive into it when I can!

**Comment by kryztoval** [comment]
If I remember correctly at the start (before the settings changed in A111 settings) the total number of steps when using img2img would be (steps * denoising strength)+1

If you are getting 41 steps you are most likely using 80 steps and 0.5 denoising strength If you set it to 0.2 and 100 steps you should get 21 real steps (or 81 steps if you set the similarity).

This can be overridden in the settings page where it says if you want img2img to use the whole set images instead of a fraction based on the denoising strength

Based on what you said the setting is set but the api is ignoring it, this is odd.

**Comment by benrugg** [comment]
@kryztoval This is really helpful. I just checked into this more, and you're exactly right. I can fix this on my end, but it seems like it would make more sense for it to be fixed in Automatic1111. Do you have any thoughts on this? If I file an issue on Automatic1111, is it likely anyone will pick it up?

**Comment by benrugg** [comment]
With more testing, I should clarify that changing the setting in Automatic111 does actually change it in the API. Maybe this has been changed since you last tried it, @amerizalde?

**Comment by benrugg** [comment]
I believe this has been fixed in Automatic1111. Closing this, but let me know if you still see it happening.
